### ISSUE TITLE
Create docker compose for Ask

### ISSUE THREAD

**Issue by jde** [coralproject/reef#32]
The Ask product has four components:

Cay
Pillar
Elkhorn
S3

Create a docker-compose file and any supporting environment files to make installing Ask as easy and intuitive as possible.

Integrate this effort with documentation efforts #31

**Comment by edefikh** [comment]
```
version: '2'
services:
  mongodata:
    image: coralproject/mongodata
    restart: always
    environment:
      - "MONGO_DUMP=https://s3.amazonaws.com/coral-demo-dataset/dump.tar.gz"
      - "MONGO_USER=${MONGO_USER}"
      - "MONGO_PASS=${MONGO_PASS}"
      - "MONGO_DB=${MONGO_DB}"
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBIT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"

  pillarapp:
    image: coralproject/pillar:release
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - "PILLAR_HOME=/opt/pillar"
      - "PILLAR_ADDRESS=:8080"
      - "MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_AUTHDB}"
      - "AMQP_EXCHANGE=PillarMQ"
      - "PILLAR_CRON=false"
      - "PILLAR_CRON_SEARCH=@every 30m"
      - "XENIA_URL=https://${FRONTEND_HOST}/xenia_api/1.0/exec/"
      - "XENIA_QUERY_PARAM=?skip=0&limit=100"
      - "XENIA_AUTH=${AUTH_TOKEN_VALUE}"
      - "AMQP_URL=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672/"
    ports:
      - "8080:8080"
    links:
      - mongodata
      - rabbitmq

  xeniaapp:
    image: coralproject/xenia
    restart: always
    environment:
      - "XENIA_MONGO_HOST=mongodata:27017"
      - "XENIA_MONGO_AUTHDB=admin"
      - "XENIA_MONGO_DB=${MONGO_DB}"
      - "XENIA_MONGO_USER=${MONGO_USER}"
      - "XENIA_MONGO_PASS=${MONGO_PASS}"
      - "XENIA_LOGGING_LEVEL=1"
      - "XENIA_HOST=:4000"
      - "XENIA_CREATE_DATABASE=${XENIA_CREATE_DATABASE}"
      - "XENIA_UPDATE_QUERY=${XENIA_UPDATE_QUERY}"
      - "XENIA_DATABASE_SCHEMA_PATH=${XENIA_DATABASE_SCHEMA_PATH}"
      - "XENIA_QUERY_UPSERT_PATH=${XENIA_QUERY_UPSERT_PATH}"
    ports:
      - "4000:4000"
    links:
      - mongodata

  cayapp:
    image: coralproject/cay:release
    restart: always
    environment:
      - "XENIA_URL=https://${FRONTEND_HOST}/xenia_api"
      - "PILLAR_URL=https://${FRONTEND_HOST}/pillar_api"
      - "ENV=staging"
      - "PROJECT=Coral Project"
      - "GAID=${GAID_VALUE}"
      - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
    ports:
      - "80:80"
    links:
      - pillarapp
      - xeniaapp
      - mongodata

  elkhorn:
    image: coralproject/elkhorn
    #build: elkhorn
    restart: always
    environment:
      - "PILLAR_URL=https://${FRONTEND_HOST}/pillar_api"
      - "AUTH_TOKEN=${AUTH_TOKEN_VALUE}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "AWS_REGION=${AWS_REGION}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_ACCESS_KEY=${AWS_ACCESS_KEY}"
    ports:
      - "4444:4444"
    links:
      - pillarapp:pillar


  proxy:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./proxy/:/etc/nginx/conf.d/
      - /etc/ssl/certs/:/etc/ssl/certs/
    links:
      - pillarapp:pillar
      - xeniaapp:xenia
      - cayapp:cay
    ports:
      - "81:80"
      - "443:443"
```
